In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.naive_bayes import GaussianNB,MultinomialNB


In [2]:
datasets = pd.read_csv("Dataset3.csv")
arr = datasets.values
print(datasets)
le = LabelEncoder()
X=datasets.iloc[:,:-1].values
Y=datasets.iloc[:,-1].values



   Outlook Temp Wind  Humidity  Class
0        R    H    F         1      0
1        R    H    T         2      0
2        O    H    F         1      1
3        R    M    F         1      1
4        S    C    F         1      1
5        O    C    T         0      0
6        O    C    T         1      1
7        R    M    F         1      0
8        O    C    F         0      1
9        S    M    F         2      1
10       R    C    T         2      0
11       O    M    T         0      1
12       O    H    F         1      1
13       S    M    T         1      0


In [3]:

outlook_encoded=le.fit_transform(X[:,0])

In [4]:
outlook_encoded

array([1, 1, 0, 1, 2, 0, 0, 1, 0, 2, 1, 0, 0, 2])

In [5]:
temp_encoded=le.fit_transform(X[:,1])

In [6]:
temp_encoded

array([1, 1, 1, 2, 0, 0, 0, 2, 0, 2, 0, 2, 1, 2])

In [7]:
Wind_encoded=le.fit_transform(X[:,2])

In [8]:
Wind_encoded

array([0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1])

In [9]:
humidity_encoded=le.fit_transform(X[:,3])

In [10]:
humidity_encoded

array([1, 2, 1, 1, 1, 0, 1, 1, 0, 2, 2, 0, 1, 1])

In [11]:
Y

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0])

In [12]:
features= np.array(list(zip(outlook_encoded,temp_encoded,Wind_encoded,humidity_encoded)),dtype=object)

print("Features: ", features)
print("Target: ",Y)

Features:  [[1 1 0 1]
 [1 1 1 2]
 [0 1 0 1]
 [1 2 0 1]
 [2 0 0 1]
 [0 0 1 0]
 [0 0 1 1]
 [1 2 0 1]
 [0 0 0 0]
 [2 2 0 2]
 [1 0 1 2]
 [0 2 1 0]
 [0 1 0 1]
 [2 2 1 1]]
Target:  [0 0 1 1 1 0 1 0 1 1 0 1 1 0]


In [13]:
from sklearn.model_selection import train_test_split
data_train, data_test, target_train, target_test = train_test_split(features,
Y, test_size = 0.05, random_state = 4)
print(data_train.shape,target_train.shape)

(13, 4) (13,)


In [14]:
data_test

array([[2, 0, 0, 1]], dtype=object)

In [15]:
import numpy as np
gnb = GaussianNB()
gnb.fit(data_train, target_train)
target_pred = gnb.predict(data_test)

In [16]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 0.0


In [17]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))
     

precision: [0. 0.]
recall: [0. 0.]


/Users/yashthakkar/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/yashthakkar/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# if Outlook is ’Rainy’, Temperature is ’Mild’, Humidity =’Normal’, and Wind = ’False’?

In [18]:
pre=[1,2,0,0]
np.array(pre).reshape(1,-1)

array([[1, 2, 0, 0]])

In [19]:
gnb.predict(np.array(pre).reshape(1,-1))

array([1])

In [20]:
gnb.predict_proba(np.array(pre).reshape(1,-1))

array([[0.21904399, 0.78095601]])

# (2) What will be the value of Play, if Outlook is ’Sunny’, Temeprature is ’Cool’, Humidity =’High’,and Wind = ’True’?

In [22]:
pre=[2,0,2,1]
gnb.predict(np.array(pre).reshape(1,-1))


array([0])

In [23]:
gnb.predict_proba(np.array(pre).reshape(1,-1))

array([[0.98517514, 0.01482486]])

# task 2


In [51]:
import sklearn
from sklearn import datasets
digit_data = sklearn.datasets.load_breast_cancer();
features = digit_data.feature_names
targets = digit_data.target_names
print(digit_data.feature_names)

['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']


In [57]:
df=pd.DataFrame(digit_data.data, columns=digit_data.feature_names)
df["target"]=pd.Series(digit_data.target)

In [58]:
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  
2          0.3613                  0.08758       0  
3          0.6638                  0.17300       0  
4          0.2364                  0.07678       0  

[5 rows x 31 columns]

In [59]:
from sklearn.model_selection import train_test_split
data_train, data_test, target_train, target_test = train_test_split(digit_data.data,
digit_data.target, test_size = 0.30, random_state = 4)
print(data_test)
data_train

[[1.442e+01 1.654e+01 9.415e+01 ... 1.414e-01 3.053e-01 8.764e-02]
 [1.205e+01 2.272e+01 7.875e+01 ... 1.092e-01 2.191e-01 9.349e-02]
 [1.953e+01 1.890e+01 1.295e+02 ... 1.980e-01 2.968e-01 9.929e-02]
 ...
 [8.196e+00 1.684e+01 5.171e+01 ... 2.564e-02 3.105e-01 7.409e-02]
 [1.221e+01 1.802e+01 7.831e+01 ... 8.829e-02 3.218e-01 7.470e-02]
 [1.129e+01 1.304e+01 7.223e+01 ... 8.750e-02 2.733e-01 8.022e-02]]


array([[2.811e+01, 1.847e+01, 1.885e+02, ..., 1.595e-01, 1.648e-01,
        5.525e-02],
       [1.979e+01, 2.512e+01, 1.304e+02, ..., 1.732e-01, 3.305e-01,
        8.465e-02],
       [1.585e+01, 2.395e+01, 1.037e+02, ..., 1.119e-01, 2.809e-01,
        6.287e-02],
       ...,
       [1.402e+01, 1.566e+01, 8.959e+01, ..., 8.216e-02, 2.136e-01,
        6.710e-02],
       [1.066e+01, 1.515e+01, 6.749e+01, ..., 0.000e+00, 2.710e-01,
        6.164e-02],
       [2.425e+01, 2.020e+01, 1.662e+02, ..., 2.248e-01, 3.222e-01,
        8.009e-02]])

In [60]:
import numpy as np
gnb = GaussianNB()
gnb.fit(data_train, target_train)
target_pred = gnb.predict(data_test)

In [61]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 0.9298245614035088


In [62]:
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

array([[ 51,   3],
       [  9, 108]])

In [63]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [0.85       0.97297297]
recall: [0.94444444 0.92307692]
