1_NB_Classifier_Weather

In [ ]:
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB, MultinomialNB

In [ ]:
weather = ['Sunny', 'Sunny', 'Overcast', 'Rainy', 'Rainy','Rainy', 'Overcast',
'Sunny', 'Sunny', 'Rainy', 'Sunny', 'Overcast', 'Overcast', 'Rainy']

temp = ['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild',
'Cool','Mild','Mild','Mild','Hot','Mild']

play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes',
'Yes','Yes','Yes','Yes','No']

In [ ]:
#create labelEncoder
le = preprocessing.LabelEncoder()

#converting string labels into numbers
weather_encoded = le.fit_transform(weather)
print("Weather :",weather_encoded)

temp_encoded = le.fit_transform(temp)
print("Temp :",temp_encoded)

label = le.fit_transform(play)
print("Play :",label)

Weather : [2 2 0 1 1 1 0 2 2 1 2 0 0 1]
Temp : [1 1 1 2 0 0 0 2 0 2 2 2 1 2]
Play : [0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [ ]:
#combining weather and temp into single listof tuple
features = tuple(zip(weather_encoded,temp_encoded))
print("Features :",features)

Features : ((2, 1), (2, 1), (0, 1), (1, 2), (1, 0), (1, 0), (0, 0), (2, 2), (2, 0), (1, 2), (2, 2), (0, 2), (0, 1), (1, 2))


In [ ]:
#create classifier
model = MultinomialNB()

#train the model using the training sets
model.fit(features,label)

MultinomialNB()

In [ ]:
#predict output
predicted = model.predict([[0,1]]) #0:overcast,1:Hot
print("Predicted Value:",predicted)

predicted= model.predict([[2,2]]) #2:Sunny, 2:Mild
print("Predicted Value:", predicted)

Predicted Value: [1]
Predicted Value: [1]


2_NB_Classifier_Iris

In [ ]:
import numpy as np
from sklearn import datasets

#Load dataset
iris = datasets.load_iris()

In [ ]:
print("Features :",iris.feature_names)
print("\nLabels :",iris.target_names)
print("\nData Shape: ",iris.data.shape)
print("\nData: ",iris.data)
print("\nTarget Shape: ",iris.target.shape)
print("\nTarget: ",iris.target)
print("\nData Type: ",type(iris.data))

newdata = iris.data[50:,:]
newtarget = iris.target[50:]

print("\nNew Data Shape: ",newdata.shape)
print("\nNew Target Shape: ",newtarget.shape)

Features : ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

Labels : ['setosa' 'versicolor' 'virginica']

Data Shape:  (150, 4)

Data:  [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.

In [ ]:
from sklearn.model_selection import train_test_split

data_train,data_test,target_train,target_test = train_test_split(newdata,newtarget,test_size=0.30,random_state=4)

In [ ]:
gnb = GaussianNB()
gnb.fit(data_train,target_train)
target_pred = gnb.predict(data_test)

In [ ]:
from sklearn import metrics
print("Accuracy: ",metrics.accuracy_score(target_test,target_pred))

Accuracy:  0.9333333333333333


In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test,target_pred)

array([[15,  2],
       [ 0, 13]])

In [ ]:
from sklearn.metrics import precision_score,recall_score
precision = precision_score(target_test,target_pred)
print('pricision: {}'.format(precision))
recall = recall_score(target_test,target_pred)
print('recall: {}'.format(recall))

pricision: 1.0
recall: 0.8823529411764706


3_NB_Classifier_Iris

In [ ]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.naive_bayes import GaussianNB,MultinomialNB
from google.colab import drive

drive.mount('/content/drive')
datasets = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Dataset1.csv")
arr = datasets.values
print(datasets)
le=LabelEncoder()
X=datasets.iloc[:,:-1].values
Y=datasets.iloc[:,4:].values
X[ : ,0] = le.fit_transform(X[ : ,0])
X[ : ,1] = le.fit_transform(X[ : ,1])
X[ : ,2] = le.fit_transform(X[ : ,2])
X[ : ,3] = le.fit_transform(X[ : ,3])
Y[ : ,0] = le.fit_transform(Y[ : ,0])
onehotencoder = OneHotEncoder()
Outlook_encoded = onehotencoder.fit_transform(X[ :, 0].reshape(-1,1)).toarray()
Temp_encoded = onehotencoder.fit_transform(X[ :, 1].reshape(-1,1)).toarray()
Humidity_encoded = onehotencoder.fit_transform(X[ :, 2].reshape(-1,1)).toarray()
Wind_encoded = onehotencoder.fit_transform(X[ :, 3].reshape(-1,1)).toarray()
Play_encoded = onehotencoder.fit_transform(Y.reshape(-1,1)).toarray()

Mounted at /content/drive
   Outlook Temp Humidity Wind Play
0        R    H   Normal    F    N
1        R    H     High    T    N
2        O    H   Normal    F    Y
3        S    M   Normal    F    Y
4        S    C   Normal    F    Y
5        S    C      Low    T    N
6        O    C   Normal    T    Y
7        R    M   Normal    F    N
8        R    C      Low    F    Y
9        S    M     High    F    Y
10       R    M     High    T    Y
11       O    M      Low    T    Y
12       O    H   Normal    F    Y
13       S    M   Normal    T    N


In [ ]:
features= np.array(list(zip(Outlook_encoded,Temp_encoded,Humidity_encoded,Wind_encoded)),dtype=object)
features = features.flatten()
print("Features: ", features)
print("Target: ",Play_encoded)

Features:  [array([0., 1., 0.]) array([0., 1., 0.]) array([0., 0., 1.])
 array([1., 0.]) array([0., 1., 0.]) array([0., 1., 0.])
 array([1., 0., 0.]) array([0., 1.]) array([1., 0., 0.])
 array([0., 1., 0.]) array([0., 0., 1.]) array([1., 0.])
 array([0., 0., 1.]) array([0., 0., 1.]) array([0., 0., 1.])
 array([1., 0.]) array([0., 0., 1.]) array([1., 0., 0.])
 array([0., 0., 1.]) array([1., 0.]) array([0., 0., 1.])
 array([1., 0., 0.]) array([0., 1., 0.]) array([0., 1.])
 array([1., 0., 0.]) array([1., 0., 0.]) array([0., 0., 1.])
 array([0., 1.]) array([0., 1., 0.]) array([0., 0., 1.])
 array([0., 0., 1.]) array([1., 0.]) array([0., 1., 0.])
 array([1., 0., 0.]) array([0., 1., 0.]) array([1., 0.])
 array([0., 0., 1.]) array([0., 0., 1.]) array([1., 0., 0.])
 array([1., 0.]) array([0., 1., 0.]) array([0., 0., 1.])
 array([1., 0., 0.]) array([0., 1.]) array([1., 0., 0.])
 array([0., 0., 1.]) array([0., 1., 0.]) array([0., 1.])
 array([1., 0., 0.]) array([0., 1., 0.]) array([0., 0., 1.])


In [ ]:
from sklearn.model_selection import train_test_split
data_train, data_test, target_train, target_test = train_test_split(X,
Play_encoded, test_size = 0.30, random_state = 4)
print(data_train.shape,target_train.shape)

(9, 4) (9, 2)


In [ ]:
import numpy as np
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
data_train = sc.fit_transform(data_train)
data_test = sc.transform(data_test)
print(data_train)
model=GaussianNB()
print(target_train)
model.fit(data_train,target_train[:,0])
target_pred0 = model.predict(data_test)
print(target_pred0)

[[ 1.5         1.20604538  0.81649658  1.11803399]
 [-1.5        -0.15075567  0.81649658 -0.89442719]
 [ 0.         -0.15075567  0.81649658 -0.89442719]
 [-1.5        -0.15075567  0.81649658 -0.89442719]
 [ 0.         -1.50755672 -0.40824829 -0.89442719]
 [ 0.         -0.15075567 -1.63299316  1.11803399]
 [ 1.5        -1.50755672 -0.40824829  1.11803399]
 [ 0.          1.20604538  0.81649658 -0.89442719]
 [ 0.          1.20604538 -1.63299316  1.11803399]]
[[1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]]
[1. 1. 0. 1. 0.]


In [ ]:
classifier1 = GaussianNB()
classifier1.fit(data_train,target_train[:,1])
target_pred1 = classifier1.predict(data_test)
print(target_pred1)

[0. 0. 1. 0. 1.]


In [ ]:
target_predicted=np.column_stack((target_pred0,target_pred1))
print(target_predicted)

[[1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]]


In [ ]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(target_test, target_predicted))

Accuracy: 0.4


In [ ]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_predicted, average=None)
recall = recall_score(target_test, target_predicted, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [0. 1.]
recall: [0.  0.4]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
import sklearn
from sklearn import datasets
digit_data = sklearn.datasets.load_digits();
features = digit_data.feature_names
targets = digit_data.target_names
print(digit_data.feature_names)

['pixel_0_0', 'pixel_0_1', 'pixel_0_2', 'pixel_0_3', 'pixel_0_4', 'pixel_0_5', 'pixel_0_6', 'pixel_0_7', 'pixel_1_0', 'pixel_1_1', 'pixel_1_2', 'pixel_1_3', 'pixel_1_4', 'pixel_1_5', 'pixel_1_6', 'pixel_1_7', 'pixel_2_0', 'pixel_2_1', 'pixel_2_2', 'pixel_2_3', 'pixel_2_4', 'pixel_2_5', 'pixel_2_6', 'pixel_2_7', 'pixel_3_0', 'pixel_3_1', 'pixel_3_2', 'pixel_3_3', 'pixel_3_4', 'pixel_3_5', 'pixel_3_6', 'pixel_3_7', 'pixel_4_0', 'pixel_4_1', 'pixel_4_2', 'pixel_4_3', 'pixel_4_4', 'pixel_4_5', 'pixel_4_6', 'pixel_4_7', 'pixel_5_0', 'pixel_5_1', 'pixel_5_2', 'pixel_5_3', 'pixel_5_4', 'pixel_5_5', 'pixel_5_6', 'pixel_5_7', 'pixel_6_0', 'pixel_6_1', 'pixel_6_2', 'pixel_6_3', 'pixel_6_4', 'pixel_6_5', 'pixel_6_6', 'pixel_6_7', 'pixel_7_0', 'pixel_7_1', 'pixel_7_2', 'pixel_7_3', 'pixel_7_4', 'pixel_7_5', 'pixel_7_6', 'pixel_7_7']


In [ ]:
from sklearn.model_selection import train_test_split
data_train, data_test, target_train, target_test = train_test_split(digit_data.data,
digit_data.target, test_size = 0.30, random_state = 4)
print(data_test)
data_train

[[ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  1. ...  0.  0.  0.]
 [ 0.  0.  5. ...  4.  0.  0.]
 ...
 [ 0.  0.  1. ...  7.  0.  0.]
 [ 0.  0.  7. ... 10.  0.  0.]
 [ 0.  0.  9. ...  0.  0.  0.]]


array([[ 0.,  0.,  5., ...,  1.,  0.,  0.],
       [ 0.,  0., 11., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 12.,  0.,  0.],
       ...,
       [ 0.,  0.,  3., ..., 10.,  0.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.],
       [ 0.,  0.,  8., ..., 10.,  1.,  0.]])

In [ ]:
import numpy as np
gnb = GaussianNB()
gnb.fit(data_train, target_train)
target_pred = gnb.predict(data_test)

In [ ]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 0.8648148148148148


In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

array([[52,  0,  0,  0,  0,  0,  0,  1,  0,  0],
       [ 0, 37,  2,  0,  0,  0,  1,  3,  6,  2],
       [ 0,  3, 44,  0,  1,  0,  0,  0,  6,  0],
       [ 0,  0,  1, 40,  0,  3,  1,  0,  8,  2],
       [ 0,  1,  0,  0, 48,  1,  2,  2,  0,  0],
       [ 0,  0,  0,  0,  0, 55,  2,  0,  0,  1],
       [ 0,  0,  1,  0,  1,  1, 49,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  1,  0, 54,  0,  0],
       [ 0,  2,  0,  1,  0,  0,  0,  2, 50,  0],
       [ 0,  3,  1,  1,  0,  0,  0,  5,  5, 38]])

In [ ]:

from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [1.         0.80434783 0.89795918 0.95238095 0.96       0.90163934
 0.89090909 0.80597015 0.66666667 0.88372093]
recall: [0.98113208 0.7254902  0.81481481 0.72727273 0.88888889 0.94827586
 0.94230769 0.98181818 0.90909091 0.71698113]


In [ ]:
predicted= model.predict([[2,1,1,0]])
print("Predicted Value:", predicted)

Predicted Value: [1.]
