# Write the function to generate random numbers from a normal distribution with mean 0 and variance 1.

In [1]:
import numpy as np

In [6]:

random_array = np.random.normal(0.0, 1.0, 100)

In [8]:
random_array

array([-1.19230078,  1.79931955,  0.25554992,  1.12687449, -1.04476384,
        0.76968798, -1.95191673, -2.70404434, -0.05476628, -0.32461073,
       -0.53160867, -0.70196881,  0.44545073,  0.00615649,  0.10693311,
       -2.02340642, -0.39570394,  0.71703157,  0.19335815,  1.18430339,
        0.80210542,  0.67631121,  0.90275066, -0.83964615, -0.81398308,
       -0.73805659,  1.27079269, -0.73156893, -0.40454019,  0.87862889,
       -0.13681779, -0.96907152, -0.93129454, -0.50366321, -0.54808862,
        1.4552101 , -2.1042709 , -1.27320954,  1.32237643,  1.26222443,
       -1.64396377, -0.62035233, -1.05903687, -0.51301648,  2.33155324,
       -1.91610939, -1.06544272, -0.06710373,  0.68008305, -0.20655634,
       -0.99139174,  1.87006382, -1.64259785,  1.41612893,  0.26342512,
        0.06915302,  1.36311196,  0.03907115,  1.0764818 , -0.80883144,
        0.30824216, -1.22322236, -1.97111094,  0.45938921, -0.14551153,
       -1.22190076, -1.62201376, -0.86227143, -0.31153746, -0.46

# Create a 1D array arr1 with 10 elements.

In [15]:
arr1=np.random.randint(0,10,10)

In [16]:
arr1

array([6, 8, 0, 1, 8, 5, 5, 4, 7, 2])

# (a) Slice this array starting from 3rd value to the end.(b) What is the result if you perform the following slicing on the given array. arr1[-4:-2]

In [17]:
arr1[3:11]

array([1, 8, 5, 5, 4, 7, 2])

In [18]:
arr1[-4:-2]

array([5, 4])

# 4. Create two numpy arrays of size 4 x 4. Write functions used to calculate determinant ofmatrix, transpose of a matrix, norm of a matrix and to perform matrix multiplication. Write all the results.

In [31]:
m1=np.random.randint(0,20,size=(4,4))
m2=np.random.randint(0,20,size=(4,4))

In [32]:
m1

array([[ 0, 11,  5,  4],
       [ 0, 16,  2, 18],
       [13,  7,  7, 15],
       [ 3, 10, 18, 17]])

In [33]:
m2

array([[16,  1,  7,  9],
       [14, 13, 12, 13],
       [ 9, 15,  2, 17],
       [ 4,  3, 19, 12]])

In [34]:
(m1*m2)

array([[  0,  11,  35,  36],
       [  0, 208,  24, 234],
       [117, 105,  14, 255],
       [ 12,  30, 342, 204]])

In [35]:
m1.T

array([[ 0,  0, 13,  3],
       [11, 16,  7, 10],
       [ 5,  2,  7, 18],
       [ 4, 18, 15, 17]])

In [36]:
m2.T

array([[16, 14,  9,  4],
       [ 1, 13, 15,  3],
       [ 7, 12,  2, 19],
       [ 9, 13, 17, 12]])

In [37]:
det = np.linalg.det(m1)

In [38]:
det

-29812.000000000004

In [39]:
det = np.linalg.det(m2)

In [40]:
det

-32901.000000000044

In [41]:
normByCols = np.linalg.norm(m1, axis=0) # Get the norm for each column.␣
normByRows = np.linalg.norm(m1, axis=1) # get the norm for each row.␣

In [42]:
normByCols

array([13.34166406, 22.93468988, 20.04993766, 29.22327839])

In [43]:
normByRows

array([12.72792206, 24.16609195, 22.18107301, 26.87005769])

In [44]:
normByCols = np.linalg.norm(m2, axis=0) # Get the norm for each column.␣
normByRows = np.linalg.norm(m2, axis=1) # get the norm for each row.␣

In [45]:
normByCols

array([23.43074903, 20.09975124, 23.62202362, 26.13426869])

In [46]:
normByRows

array([19.67231557, 26.03843313, 24.4744765 , 23.02172887])

In [48]:
from sklearn.datasets import load_iris

In [52]:
Data=load_iris()
import pandas as pd

In [53]:
df=pd.DataFrame(Data.data, columns=Data.feature_names)
df["target"]=pd.Series(Data.target)

In [54]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [56]:
X=df.iloc[1:5,:]

In [57]:
X

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
1       0  
2       0  
3       0  
4       0

In [58]:
X=df.iloc[:,2:5]

In [60]:
X

petal length (cm)  petal width (cm)  target
0                  1.4               0.2       0
1                  1.4               0.2       0
2                  1.3               0.2       0
3                  1.5               0.2       0
4                  1.4               0.2       0
..                 ...               ...     ...
145                5.2               2.3       2
146                5.0               1.9       2
147                5.2               2.0       2
148                5.4               2.3       2
149                5.1               1.8       2

[150 rows x 3 columns]