In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score

In [2]:
from sklearn import linear_model
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_breast_cancer
Data = load_breast_cancer()
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import BernoulliNB

In [3]:
lr=linear_model.LogisticRegression()
dt=DecisionTreeClassifier()
bn=BernoulliNB()

In [4]:
df=pd.DataFrame(Data.data, columns=Data.feature_names)
df["target"]=pd.Series(Data.target)

In [5]:
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  
2          0.3613                  0.08758       0  
3          0.6638                  0.17300       0  
4          0.2364                  0.07678       0  

[5 rows x 31 columns]

In [6]:
df2=df.sample(frac=1)

In [7]:
df2.shape

(569, 31)

In [8]:
hold_on_data=df2.iloc[0:285,:]

In [9]:
hold_on_data.shape

(285, 31)

In [10]:
hold_on_data

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
380       11.270         12.96           73.16      386.3          0.12370   
295       13.770         13.27           88.06      582.7          0.09198   
549       10.820         24.21           68.89      361.6          0.08192   
341        9.606         16.84           61.64      280.5          0.08481   
193       12.340         26.86           81.15      477.4          0.10340   
..           ...           ...             ...        ...              ...   
231       11.320         27.08           71.76      395.7          0.06883   
226       10.440         15.46           66.62      329.6          0.10530   
31        11.840         18.70           77.93      440.6          0.11090   
129       19.790         25.12          130.40     1192.0          0.10150   
508       16.300         15.70          104.70      819.8          0.09427   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
380           0.11110        0.079000             0.055500         0.2018   
295           0.06221        0.010630             0.019170         0.1592   
549           0.06602        0.015480             0.008160         0.1976   
341           0.09228        0.084220             0.022920         0.2036   
193           0.13530        0.108500             0.045620         0.1943   
..                ...             ...                  ...            ...   
231           0.03813        0.016330             0.003125         0.1869   
226           0.07722        0.006643             0.012160         0.1788   
31            0.15160        0.121800             0.051820         0.2301   
129           0.15890        0.254500             0.114900         0.2202   
508           0.06712        0.055260             0.045630         0.1711   

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
380                 0.06914  ...          20.53            84.93       476.1   
295                 0.05912  ...          16.93            94.17       661.1   
549                 0.06328  ...          31.45            83.90       505.6   
341                 0.07125  ...          23.07            71.25       353.6   
193                 0.06937  ...          39.34           101.70       768.9   
..                      ...  ...            ...              ...         ...   
231                 0.05628  ...          33.75            79.82       452.3   
226                 0.06450  ...          19.80            73.47       395.4   
31                  0.07799  ...          28.12           119.40       888.7   
129                 0.06113  ...          33.58           148.70      1589.0   
508                 0.05657  ...          17.76           109.80       928.2   

     worst smoothness  worst compactness  worst concavity  \
380           0.16100             0.2429          0.22470   
295           0.11700             0.1072          0.03732   
549           0.12040             0.1633          0.06194   
341           0.12330             0.3416          0.43410   
193           0.17850             0.4706          0.44250   
..                ...                ...              ...   
231           0.09203             0.1432          0.10890   
226           0.13410             0.1153          0.02639   
31            0.16370             0.5775          0.69560   
129           0.12750             0.3861          0.56730   
508           0.13540             0.1361          0.19470   

     worst concave points  worst symmetry  worst fractal dimension  target  
380               0.13180          0.3343                  0.09215       1  
295               0.05802          0.2823                  0.06794       1  
549               0.03264          0.3059                  0.07626       1  
341               0.08120          0.2982                  0.09825       1  
193               0.14590          0.3215                  0.120

In [11]:
df1=df2.iloc[286:569,:]

In [12]:
y=df1.iloc[:,-1]

In [13]:
y

42     0
119    0
131    0
142    1
353    0
      ..
70     0
332    1
555    1
438    1
261    0
Name: target, Length: 283, dtype: int64

In [14]:
X=df1.iloc[:,:-1]

In [15]:
X

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
42         19.07         24.81          128.30     1104.0          0.09081   
119        17.95         20.01          114.20      982.0          0.08402   
131        15.46         19.48          101.70      748.9          0.10920   
142        11.43         17.31           73.66      398.0          0.10920   
353        15.08         25.74           98.00      716.6          0.10240   
..           ...           ...             ...        ...              ...   
70         18.94         21.31          123.60     1130.0          0.09009   
332        11.22         19.86           71.94      387.3          0.10540   
555        10.29         27.61           65.67      321.4          0.09030   
438        13.85         19.60           88.68      592.6          0.08684   
261        17.35         23.06          111.00      933.1          0.08662   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
42            0.21900        0.210700             0.099610         0.2310   
119           0.06722        0.072930             0.055960         0.2129   
131           0.12230        0.146600             0.080870         0.1931   
142           0.09486        0.020310             0.018610         0.1645   
353           0.09769        0.123500             0.065530         0.1647   
..                ...             ...                  ...            ...   
70            0.10290        0.108000             0.079510         0.1582   
332           0.06779        0.005006             0.007583         0.1940   
555           0.07658        0.059990             0.027380         0.1593   
438           0.06330        0.013420             0.022930         0.1555   
261           0.06290        0.028910             0.028370         0.1564   

     mean fractal dimension  ...  worst radius  worst texture  \
42                  0.06343  ...         24.09          33.17   
119                 0.05025  ...         20.58          27.83   
131                 0.05796  ...         19.26          26.00   
142                 0.06562  ...         12.78          26.76   
353                 0.06464  ...         18.51          33.22   
..                      ...  ...           ...            ...   
70                  0.05461  ...         24.86          26.58   
332                 0.06028  ...         11.98          25.78   
555                 0.06127  ...         10.84          34.91   
438                 0.05673  ...         15.63          28.01   
261                 0.05307  ...         19.85          31.47   

     worst perimeter  worst area  worst smoothness  worst compactness  \
42            177.40      1651.0            0.1247            0.74440   
119           129.20      1261.0            0.1072            0.12020   
131           124.90      1156.0            0.1546            0.23940   
142            82.66       503.0            0.1413            0.17920   
353           121.20      1050.0            0.1660            0.23560   
..               ...         ...               ...                ...   
70            165.90      1866.0            0.1193            0.23360   
332            76.91       436.1            0.1424            0.09669   
555            69.57       357.6            0.1384            0.17100   
438           100.90       749.1            0.1118            0.11410   
261           128.20      1218.0            0.1240            0.14860   

     worst concavity  worst concave points  worst symmetry  \
42           0.72420               0.24930          0.4670   
119          0.22490               0.11850          0.4882   
131          0.37910               0.15140          0.2837   
142          0.07708               0.06402          0.2584   
353          0.40290               0.15260          0.2654   
..               ...                   ...             ...   
70           0.26870               0.17890         

In [16]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X=sc.fit_transform(X)

In [17]:
X

array([[ 1.35047238,  1.29468299,  1.43844083, ...,  1.89120407,
         2.46168989,  0.95654556],
       [ 1.04199963,  0.18750469,  0.87382118, ..., -0.03597703,
         2.76804223, -1.2976488 ],
       [ 0.35619862,  0.06525375,  0.37327184, ...,  0.44876501,
        -0.18710185, -0.29015224],
       ...,
       [-1.0677336 ,  1.94053699, -1.06951156, ..., -0.43717841,
        -1.07003243, -0.15075019],
       [-0.08723095,  0.09293321, -0.14810034, ..., -0.91411153,
        -0.65530072, -0.87521838],
       [ 0.87674638,  0.89102423,  0.74568055, ..., -0.56860391,
        -0.74344927, -1.08432144]])

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

In [19]:
lr.fit(X_train,y_train)
dt.fit(X_train,y_train)
bn.fit(X_train,y_train)

BernoulliNB()

In [20]:
h_X=hold_on_data.iloc[:,:-1]
h_y=hold_on_data.iloc[:,-1]

In [21]:
h_X

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
380       11.270         12.96           73.16      386.3          0.12370   
295       13.770         13.27           88.06      582.7          0.09198   
549       10.820         24.21           68.89      361.6          0.08192   
341        9.606         16.84           61.64      280.5          0.08481   
193       12.340         26.86           81.15      477.4          0.10340   
..           ...           ...             ...        ...              ...   
231       11.320         27.08           71.76      395.7          0.06883   
226       10.440         15.46           66.62      329.6          0.10530   
31        11.840         18.70           77.93      440.6          0.11090   
129       19.790         25.12          130.40     1192.0          0.10150   
508       16.300         15.70          104.70      819.8          0.09427   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
380           0.11110        0.079000             0.055500         0.2018   
295           0.06221        0.010630             0.019170         0.1592   
549           0.06602        0.015480             0.008160         0.1976   
341           0.09228        0.084220             0.022920         0.2036   
193           0.13530        0.108500             0.045620         0.1943   
..                ...             ...                  ...            ...   
231           0.03813        0.016330             0.003125         0.1869   
226           0.07722        0.006643             0.012160         0.1788   
31            0.15160        0.121800             0.051820         0.2301   
129           0.15890        0.254500             0.114900         0.2202   
508           0.06712        0.055260             0.045630         0.1711   

     mean fractal dimension  ...  worst radius  worst texture  \
380                 0.06914  ...         12.84          20.53   
295                 0.05912  ...         14.67          16.93   
549                 0.06328  ...         13.03          31.45   
341                 0.07125  ...         10.75          23.07   
193                 0.06937  ...         15.65          39.34   
..                      ...  ...           ...            ...   
231                 0.05628  ...         12.08          33.75   
226                 0.06450  ...         11.52          19.80   
31                  0.07799  ...         16.82          28.12   
129                 0.06113  ...         22.63          33.58   
508                 0.05657  ...         17.32          17.76   

     worst perimeter  worst area  worst smoothness  worst compactness  \
380            84.93       476.1           0.16100             0.2429   
295            94.17       661.1           0.11700             0.1072   
549            83.90       505.6           0.12040             0.1633   
341            71.25       353.6           0.12330             0.3416   
193           101.70       768.9           0.17850             0.4706   
..               ...         ...               ...                ...   
231            79.82       452.3           0.09203             0.1432   
226            73.47       395.4           0.13410             0.1153   
31            119.40       888.7           0.16370             0.5775   
129           148.70      1589.0           0.12750             0.3861   
508           109.80       928.2           0.13540             0.1361   

     worst concavity  worst concave points  worst symmetry  \
380          0.22470               0.13180          0.3343   
295          0.03732               0.05802          0.2823   
549          0.06194               0.03264          0.3059   
341          0.43410               0.08120          0.2982   
193          0.44250               0.14590          0.3215   
..               ...                   ...             ...   
231          0.10890               0.02083         

In [22]:
h_X=sc.fit_transform(h_X)

In [23]:
x1=lr.predict(h_X)
x2=dt.predict(h_X)
x3=bn.predict(h_X)

In [24]:
x1

array([1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1])

In [25]:
x2

array([1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1])

In [26]:
x3

array([1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0])

In [27]:
df3=pd.DataFrame(data=[x1,x2,x3])

In [28]:
df4=df3.T

In [29]:
df4

0  1  2
0    1  1  1
1    1  1  1
2    1  1  1
3    1  1  1
4    0  0  0
..  .. .. ..
280  1  1  1
281  1  1  1
282  0  0  0
283  0  0  0
284  1  1  0

[285 rows x 3 columns]

In [30]:
lr2=LogisticRegression()

In [31]:
df4_X=df4.iloc[:,:]
df4_Y=h_y

In [32]:
df4_X

0  1  2
0    1  1  1
1    1  1  1
2    1  1  1
3    1  1  1
4    0  0  0
..  .. .. ..
280  1  1  1
281  1  1  1
282  0  0  0
283  0  0  0
284  1  1  0

[285 rows x 3 columns]

In [33]:
df4_Y

380    1
295    1
549    1
341    1
193    0
      ..
231    1
226    1
31     0
129    0
508    1
Name: target, Length: 285, dtype: int64

In [34]:
lr2.fit(df4_X,df4_Y)

LogisticRegression()

In [35]:
X_test=sc.fit_transform(X_test)

In [36]:
X_test

array([[ 0.40703602, -0.04055927,  0.53518826, ...,  1.241749  ,
         1.49766504,  0.88302029],
       [-0.08432677,  0.05303098, -0.14993312, ..., -0.85098624,
        -0.61321392, -0.8393691 ],
       [-1.05929398, -1.05281165, -1.07681828, ..., -1.50723335,
        -0.10133796, -0.4621615 ],
       ...,
       [-0.54982835, -1.1710309 , -0.54568184, ..., -0.76191639,
        -0.32802588, -0.17229714],
       [-0.25242456, -0.87794566, -0.32139943, ..., -1.30987191,
        -0.4450261 , -0.13198488],
       [ 1.15183855,  1.41008952,  1.19352965, ...,  0.85325287,
         0.52144446,  0.53844643]])

In [37]:
x4=lr.predict(X_test)
x5=dt.predict(X_test)
x6=bn.predict(X_test)

In [38]:
df5=pd.DataFrame(data=[x4,x5,x6])

In [39]:
df6=df5.T

In [40]:
df6

0  1  2
0   0  0  0
1   1  1  1
2   1  1  1
3   1  1  1
4   1  1  1
.. .. .. ..
89  0  0  0
90  1  1  1
91  1  1  1
92  1  1  1
93  0  0  0

[94 rows x 3 columns]

In [41]:
df6_X=df6.iloc[:,:]


In [42]:
final=lr2.predict(df6_X)

In [43]:
from sklearn.metrics import accuracy_score

In [56]:
accuracy_score(y_test, final)


0.9893617021276596

In [55]:
precision = precision_score(y_test, final, average=None)
recall = recall_score(y_test, final, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [1.         0.98214286]
recall: [0.97435897 1.        ]


In [57]:
from sklearn.ensemble import StackingClassifier

In [58]:
df_X=df.iloc[:,:-1]
df_y=df.iloc[:,-1]

In [59]:
df_X=sc.fit_transform(df_X)

In [60]:
df_X.shape

(569, 30)

In [61]:
df_X_train, df_X_test, df_y_train, df_y_test = train_test_split(df_X, df_y, test_size=0.33)

In [62]:
estimators=[('lr',LogisticRegression()),('dt',DecisionTreeClassifier()),('bn',BernoulliNB())]

In [63]:
clf = StackingClassifier(estimators=estimators, final_estimator=LogisticRegression())

In [64]:
clf.fit(df_X_train,df_y_train)

StackingClassifier(estimators=[('lr', LogisticRegression()),
                               ('dt', DecisionTreeClassifier()),
                               ('bn', BernoulliNB())],
                   final_estimator=LogisticRegression())

In [65]:
final1=clf.predict(df_X_test)

In [66]:
accuracy_score(df_y_test, final1)

0.9893617021276596

In [67]:
precision = precision_score(df_y_test, final1, average=None)
recall = recall_score(df_y_test, final1, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [1.         0.98412698]
recall: [0.96875 1.     ]
